apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
      - name: django
        image: https://presley.jfrog.io/artifactory/docker-local-docker/
        ports:
          - containerPort: 8000
        env:
          - name: DATABASE_URL
            value: "sqlite:///db.sqlite3"  
