apiVersion: v1
kind: Service
metadata:
  name: django-backend
  namespace: my-app
spec:
  type: ClusterIP
  selector:
    app: django-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
